### ISSUE TITLE
Box zoom tool

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#100]
Add a tool to draw a box to zoom to an area.  Remove the [+ -] zoom controls.

Rationale;  it's a massive pain in the arse to zoom around to a particular area.

**Comment by Alpal94** [comment]
Box zoom is currently enabled if shift is pressed.  In my mind the zoom controls could still be useful for zooming out if user only has access to a laptop without a proper mouse or touch screen.  The user experience of zooming out with the controls is not as bad as zooming in.

**Comment by Alpal94** [comment]
Amir desires some modifications to the Box Zoom Tool.

**Comment by Alpal94** [comment]
Changes requested by Amir included box zoom out, zoom in on click, extended zoom and modifications to zoom tool icons.  Changes pushed to corresponding branch and initiated pull request.
