### ISSUE TITLE
Add Markdown support for description

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#107]
Add markdown support for the description field of listings and a profile bio.  You will have to test the inputs will work with the contract write and don't get mangled.

Use a https://github.com/rexxars/react-markdown to render the markdown in the appropriate place.

Rationale is to allow people to style and create links in their descriptions.

**Comment by Alpal94** [comment]
Implemented in branch [#107-Add-Markdown-support-for-description](url) and pull request submitted.
