### ISSUE TITLE
Rich text preview meta tags for listings

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#114]
If you paste a link to a listing in Telegram (eg. http://demo.soar.earth/browse/9ba988dd86d3f4ed32a53c49b5deb563) , it will attempt to generate a rich preview based on the pages meta tag `og:title`, `og:description` and `og:image`.   Unfortunately, these pages are generated dynamically so getting there isn't any easy way to have them update that a bot or crawler will understand.

I've had a quick experiment with these:
 * https://github.com/s-yadav/react-meta-tags
 * https://github.com/nfl/react-helmet
 * https://github.com/kodyl/react-document-meta

Which all claim to do it but don't.

This would be a seriously nice to have as we could direct people from telegram to the demo.

**Comment by Alpal94** [comment]
Changes pushed to master
