### ISSUE TITLE
Remove sensitive information from source code

### ISSUE THREAD

**Issue by mtlacbaba** [SoarEarth/soar-platform-demo#19]

**Comment by ChrisLowe-Takor** [comment]
I'm guessing this is the MapBox API keys. Not a big deal.

**Comment by mtlacbaba** [comment]
It is Google API key for reverse geocoding

**Comment by ChrisLowe-Takor** [comment]
We've hit our usage limit on MapBox.  We will need to set this up before I put credit card details in or we risk exposing a paid service.
