### ISSUE TITLE
Coordinates don't wrap around prime meridian

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#22]
When selecting the location for an image if you continuously drag a marker to the left or right you will stop getting geocoded location names.   It looks like a bug in leaflet where longitudes don't wrap around the meridian and fall outside the 180..180 range of valid longitudes.

We will have to manually wrap before creating the WKT or attempting to geocode.

**Comment by Alpal94** [comment]
Fixed and pushed to browser branch.
