### ISSUE TITLE
Missing fields error in Upload form

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#24]
Some fields are mandatory for the Upload form such as:

- Title
- Description
- Date taken
- Drone make and manufacturer
- Location
- Altitude

If the user attempts to progress with the form without these fields the button either does nothing or uploads incomplete photos.   These need to have error messages using Material-UI that highlights the missing fields

**Comment by Alpal94** [comment]
Committed changes to browser.
