### ISSUE TITLE
Upload progress page

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#26]
After #25 is done I'd like another page once the user has triggered the upload which shows the progress of the upload.

Something along the lines of:

  ✓  Preparing to Upload
  ✓  Meta mask transaction
  ✓  Waiting for confirmation
  ✓  Uploading file
  ✓  Done

Once this is done we should then open the map at the location of the new content.

**Comment by Alpal94** [comment]
Completed and pushed to browser branch, will likely need changes to appearance however.
