### ISSUE TITLE
Small UI changes for presentation

### ISSUE THREAD

**Issue by mtlacbaba** [SoarEarth/soar-platform-demo#36]
- change starting zoom level and position to show whole world 
- reupload images with meaningful titles and description and upload only high-quality photos
- change map in upload form to use Mapbox
- added proper error messages to upload process

**Comment by ChrisLowe-Takor** [comment]
- Clicking on the marker popup preview image should open full browse card.

**Comment by ChrisLowe-Takor** [comment]
Not re-uploading content as we will need to deploy a new contract with #39

**Comment by ChrisLowe-Takor** [comment]
PR #41
