### ISSUE TITLE
Final step of Uploading requires better UX

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#64]
Based on hallway testing the final step of uploading can cause some confusion.  After they have pressed `Upload` MetaMask pops up asking to confirm the transaction.  That is obvious to us that you need to accept, wait, then accept a second time but not to the user.

We will need to design a better UX for guiding the user through this final step.

It should be noted that this is temporary as the Sponsorship model will take step away from the user.  However they will then need to be onboarded about this final step that is done by a third party and can take some time.

**Comment by Alpal94** [comment]
I have completed a functional implementation of an improvement to the upload experience.  May require a second opinion on UI.
