### ISSUE TITLE
Entering tags should accept comma

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#65]
I noticed during Hallway testing that some users fail to read the placeholder instructions when entering tags.  Instead of pressing ENTER they comma seperate tags.   This would result in a single tag such as `Beach, Holiday, Paradise`  instead of three seperate tags.

To fix, lets detect the comma input and set it as the start of a new tag.

It looks like `material-ui-chip-input` already supports this. See https://github.com/TeamWertarbyte/material-ui-chip-input/pull/38

**Comment by Alpal94** [comment]
I have merged changes to fix this issue.  It was a very minor change, only one line added so there was no need to review the changes.
