### ISSUE TITLE
Add news items

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [SoarEarth/soar-platform-demo#97]
The news items in the side drawer are empty because there is no content for them.

Create a few listings with the News tag.  Something interesting and news worthy that has a drone image.

**Comment by Alpal94** [comment]
The branch [#89-Increase-size-of-preview-image](url) is able to detect wether there are enough news articles, if there are not enough it fills the browser with other content.  News items will still need to be entered but this will get rid of the black space in the meantime.
